CREATE DATABASE customer_behavior;
use customer_behavior;
select * from customer limit 20;
#Q1 Total revenue generated by male and female customer?
select gender,sum(purchase_amount) as Total_revenue
 from customer
 group by gender;

#Q2 which customer used a discount but still spent more than average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied ='Yes' and purchase_amount >  (select avg(purchase_amount)  from customer);

 #Q4 what are Top 5 products with highest average review rating?
 select item_purchased as product,round(avg(review_rating),2)as average_rating
 from customer
 group by item_purchased
 order by average_rating desc 
 limit 5;
 
# select * from customer limit 20;
 
 #Q5 Compare the average Purchase Amount between standard and Express Shhipping
--  select avg(purchase_amount),shipping_type from
--  customer where shipping_type = 'Express'
--  union
--   select avg(purchase_amount),shipping_type from
--  customer where shipping_type = 'standard';
--  or
 select avg(purchase_amount),shipping_type 
 from customer 
 where shipping_type in ('Express','standard')
 group by shipping_type;

#Q5 Do subscribed customer spend more? Compare Average Spend and Total revenue between subscribers and non subscribers?
select count(customer_id), avg(purchase_amount),sum(purchase_amount) as Total_revenue,subscription_status
from customer 
where subscription_status in ('Yes','No')
group by subscription_status
order by Total_revenue desc;

#Q6 Which 5 products have highest percentage of purchases with discount applied?
	SELECT item_purchased,
       ROUND(
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
           * 100.0 / COUNT(*),
       2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
 
 
 #Q7: Segment customers into New,Returning and loyal based on their total number of previous purchases and show the count of each segment
 
  #select * from customer limit 20;
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_type,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_type;
#Q8 WHAt are top 3 most purchased products within each category
select * from (
select  COUNT(customer_id) as total_orders,item_purchased,category,row_number() over (partition by category order by count(customer_id)  desc) as rk 
from customer
group by item_purchased,category) as c
where rk <=3;

#Q9 Are customers who are repeat buyers (More than 5 previous purchases) also likely to subscribe 
select count(customer_id) , subscription_status
from customer 
where previous_purchases >5 
group by subscription_status;

-- Q10 what is revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_contribution
from customer
group by age_group;



